name: 'Kubeflow Upload Pipeline'
description: 'Upload Kubeflow pipeline'
inputs:
  kubeflowEndpoint:  
    description: 'Kubeflow API endpoint base URL format http://yourURL/'
    required: true
    default: ''
  bearerToken:  
    description: 'Do not input raw tokens. Read more on how to handle secrets at https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets.'
    required: false
    default: ''
  kubeflowPipelineTask:  # needs a picklist
    description: 'Input either uploadNew or uploadNewVersion'
    required: true
    default: 'uploadNew'
  pipelineFilePath:  
    description: 'File path of the pipeline file to be uploaded. Must be a compressed .tar.gz file.'
    required: true
    default: ''
  newPipelineName:  
    description: 'Pipeline name for new upload.'
    required: false
    default: ''
  existingPipelineName:  
    description: 'Existing pipeline name to create new version.'
    required: false
    default: ''
  versionName:  
    description: 'New pipeline version name.'
    required: false
    default: ''
outputs:
  kf_pipeline_name: 
    description: 'Name of the pipeline utilized.'
  kf_pipeline_id:
    description: 'ID of the pipeline utilized.'
  kf_pipeline_version_name:
    description: 'Name of the new pipeline version.'
  kf_pipeline_version_id:
    description: 'ID of the new pipeline version.'
runs:
  using: 'node12'
  main: 'index.js'