# Pipeline for testing the tasks created within this project

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: KubeflowUploadPipeline@0
  inputs:
    kubeflowEndpoint: 'http://52.149.62.186/'
    kubeflowPipelineTask: 'uploadNewVersion'
    pipelineFilePath: '$(System.DefaultWorkingDirectory)/src/Tasks/Upload_Pipeline/Tests/pipeline.py.tar.gz'
    existingPipelineName: 'azdoTestPipeline'
    versionName: 'azdoTestV5'
- task: KubeflowExperimentRun@0
  inputs:
    kubeflowEndpoint: 'http://52.149.62.186/'
    pipeline: 'azdoTestPipeline'
    useDefaultVersion: false
    pipelineVersion: 'azdoTestV5'
    runName: 'newRun'
    pipelineParams: '[{"name":"resource_group", "value":"kubeflow-integration-rg"}, {"name":"workspace", "value":"kubeflow-integration-aml"}]'
    experiment: 'useExistingExperiment'
    experimentName: 'azdoTestExperiment'
